name: Pull Request Template

description: Use this template for creating pull requests.

body:
  - type: textarea
    id: purpose
    attributes:
      label: Purpose
      description: Please provide a brief overview of the purpose of this pull request.
    validations:
      required: true
